# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4293f480fe7478b444aa500afa7c26bad9c4426881595133b33c4743682be039991654cf66cd9ed7277b8e0428dcef9eda439fb311ace25a0ba998d484f2f5ba

test:
  secret_key_base: cabfaf614b3b1fa73f8563c04de0f846672506e829a53f549f7d009ab50c5b3db655f04cb278acabc33a0fecd78748d01746bf81696cbc4638412a42d56f1028

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
